### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by l1346792580123** [yifita/DSS#11]
When I try to run the demo in the readme, I get the following error:
Traceback (most recent call last):
  File "train_mvr.py", line 75, in <module>
    cfg, camera_model=train_dataset.get_cameras(), device=device)
  File "/home/llx/packages/DSS/config.py", line 184, in create_model
    renderer = create_renderer(cfg.renderer).to(device)
  File "/home/llx/packages/DSS/config.py", line 244, in create_renderer
    Raster = get_class_from_string(render_opt.raster_type)
  File "/home/llx/packages/DSS/DSS/utils/__init__.py", line 71, in get_class_from_string
    mod = importlib.import_module(cls_str[:i])
  File "/home/llx/anaconda3/envs/vibe/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/llx/packages/DSS/DSS/core/rasterizer.py", line 21, in <module>
    from .. import _C, logger_py
ImportError: /home/llx/packages/DSS/DSS/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Z25RasterizePointsCoarseCudaRKN2at6TensorES2_S2_S2_iii

my environment is python3.7 pytorch1.4. I follow the installation to install except:
my pytorch3d is installed from source(in my test it works)
my pytorch version is 1.4 and cuda version is cuda10.0
I install fvcore and iopath with pip
Does these matter?
How can I solve this problem?

**Comment by l1346792580123** [comment]
I have found that there are some functions used in this repository like(gpuAtomicAdd) are not defined in pytorch1.4.  Now I change to pytorch1.6 and it works fine.
