### ISSUE TITLE
ValueError: Invalid vertices in file.

### ISSUE THREAD

**Issue by pbonazzi** [yifita/DSS#22]
If I try to preprocess the Kangaroo point cloud (`example_data/pointclouds/Kangaroo_V10k.ply`) I get : 

```
Traceback (most recent call last):
  File "scripts/create_mvr_data_from_mesh.py", line 106, in <module>
    verts, faces = load_ply(mesh_path)
  File "/home/bpietro/.conda/envs/DSS/lib/python3.8/site-packages/pytorch3d/io/ply_io.py", line 656, in load_ply
    raise ValueError("Invalid vertices in file.")
ValueError: Invalid vertices in file.
```
As noted in https://github.com/facebookresearch/pytorch3d/issues/363 , 
I have downloaded the last stable version of pytorch with :
`pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'`
And tried their solution to at least load the point cloud , but then , but then the code breaks as in #19 and the data cannot be loaded .

```
Traceback (most recent call last):
  File "scripts/create_mvr_data_from_mesh.py", line 106, in <module>
    pointcloud = IO().load_pointcloud(path=mesh_path)
  File "/home/bpietro/.conda/envs/DSS/lib/python3.8/site-packages/pytorch3d/io/pluggable.py", line 187, in load_pointcloud
    pointcloud = pointcloud_interpreter.read(
  File "/home/bpietro/.conda/envs/DSS/lib/python3.8/site-packages/pytorch3d/io/ply_io.py", line 1442, in read
    data = _load_ply(f=path, path_manager=path_manager)
  File "/home/bpietro/.conda/envs/DSS/lib/python3.8/site-packages/pytorch3d/io/ply_io.py", line 1029, in _load_ply
    raise ValueError("Unexpected form of faces data.")
```

**Comment by lxxue** [comment]
Thanks for pointing it out. You can checkout the branch `fix/load_ply` where I use `open3d` to load ply files instead. The rendered images look good to me.

**Comment by pbonazzi** [comment]
Super , thanks
