### ISSUE TITLE
Issue with running demo

### ISSUE THREAD

**Issue by Zvyozdo4ka** [yifita/DSS#28]
Why it is not possible to run demo? Why does It raise this issues? What is it required as input?

``` 
python scripts/create_mvr_data_from_mesh.py --points example_data/mesh/yoga6.ply --output example_data/images --num_cameras 128 --image-size 512 --tri_color_light --point_lights --has_specular
  0%|                                                                                                                                                              | 0/128 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "scripts/create_mvr_data_from_mesh.py", line 241, in <module>
    imageio.imwrite(os.path.join(depth_dir, "%06d.exr" % idx),
  File "/home/admin/anaconda3/envs/DSS/lib/python3.8/site-packages/imageio/core/functions.py", line 303, in imwrite
    writer = get_writer(uri, format, "i", **kwargs)
  File "/home/admin/anaconda3/envs/DSS/lib/python3.8/site-packages/imageio/core/functions.py", line 226, in get_writer
    raise ValueError(
ValueError: Could not find a format to write the specified file in single-image mode
```

Is there any other detailed documentation? And would be denoising function available?

**Comment by romantic-black** [comment]
I'm facing the same problem and I use `cv2` instead of `imageio` to solve it.
Before `import  cv2` add `os.environ["OPENCV_IO_ENABLE_OPENEXR"]="1"`
```python
                cv2.imwrite(os.path.join(depth_dir, "%06d.exr" % idx),
                                dense_depths[b, ...].cpu().numpy())
```

**Comment by Zvyozdo4ka** [comment]
@romantic-black Thank you!
