### ISSUE TITLE
problem with dense depth

### ISSUE THREAD

**Issue by Zvyozdo4ka** [yifita/DSS#29]
it was so hard to run this project, but after many failures to get any results there is always an issue related with getting dense depth as exr file. Did anyone have such problem?

```
Traceback (most recent call last):
  File "scripts/create_mvr_data_from_mesh.py", line 251, in <module>
    imageio.imwrite(os.path.join(depth_dir, "%06d.exr" % idx),
  File "/home/admin/anaconda3/envs/DSS/lib/python3.8/site-packages/imageio/core/functions.py", line 303, in imwrite
    writer = get_writer(uri, format, "i", **kwargs)
  File "/home/admin/anaconda3/envs/DSS/lib/python3.8/site-packages/imageio/core/functions.py", line 226, in get_writer
    raise ValueError(
ValueError: Could not find a format to write the specified file in single-image mode

```

And can we expect denoising function back?  
And i did not get the use of this method. On the left side the sculpture produced by Poisson Reconstruction Plugin Cloud Compare, and the right side the result from your DSS project. I did not understand the use of splatting, the model just loses necessary details.
![image](https://github.com/yifita/DSS/assets/74532816/16144f18-ce59-46c8-8e3a-9d377ec4e79c)

**Comment by romantic-black** [comment]
I'm facing the same problem and I use `cv2` instead of `imageio` to solve it.
Before `import  cv2` add `os.environ["OPENCV_IO_ENABLE_OPENEXR"]="1"`
```python
                cv2.imwrite(os.path.join(depth_dir, "%06d.exr" % idx),
                                dense_depths[b, ...].cpu().numpy())
```
